server:
  servlet:
    context-path: /front
spring:
  profiles:
    active: local
  jackson:
    serialization:
      fail-on-empty-beans: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    thymeleaf:
      cache: false #使用Thymeleaf模板引擎，关闭缓存
  redis:
    database: 0
    host: 192.168.10.14
    port: 6379
    password:
mycloud:
  register:
    registerByMobileLogin: true #未注册手机 通过登录直接注册
    baseCapacity: 524288000 #基础容量 500G 单位为Byte
  redis:
    open: true
  hdfsBasePath: /yefeng
  fileIdSize: 40
  # 线程池配置
  thread-pool:
    # 公用线程池
    common:
      corePoolSize: 1
      maximumPoolSize: 5
      keepAliveTime: 0
      queueCapacity: 20480

  upload:
    idSize: 32
    tokenExpire: 600 #600 sec  is 10 minutes
  download:
    urlExpireTime: 3600 #downloadUrltoken失效时间 默认10分钟600秒
  useractive:
    tokenExpire: 7200 #7200 sec  is 2 hours
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致

verification-code:
  sender:
    type: email
