server:
  port: 8081
  servlet:
    context-path: /hdfs

hdfs:
  hdfsPath: hdfs://dockerhadoop:9000
  hdfsName: root

spring:
  servlet:
    multipart:
      max-request-size: 10240MB
      max-file-size: 5120MB

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    thymeleaf:
      cache: false #使用Thymeleaf模板引擎，关闭缓存


mycloud:
  downloadToken:
    enable: true #是否需要开启下载token校验
    position: parameter #默认为header 可以选项 header 和 parameter