server:
  port: 9527  #端口号
  address: 0.0.0.0


spring:
  profiles:
    active: dev
  cloud:
    gateway: #网关路由配置
      routes:
        - id: cloud-netdisk-hadoop   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: http://dockerhadoop:8081          #匹配后提供服务的路由地址
          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/hdfs/**   #/dept/list/**               #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET,POST,PUT,DELETE #只能时 GET 请求时，才能访问
        - id: netdisk-cloud-front
          uri: lb://netdisk-cloud-front
          predicates:
            - Path=/front
            - Method=GET,POST,PUT,DELETE



logging:
  path: hgatewayLogs
  level:
    root: info
system:
  whitelist:
    - /hdfs/api/v1/hdfs/file
    - /hdfs/api/v1/hdfs/file/list
    - /front/*